baseURL: https://maoze-porfolio.netlify.app/
languageCode: en-us
title: Forty
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Maoze Li. I am a current Masters in Financial Analysis student at London Business School
  blog: {}
  contact:
    address:
      - city: London, NW1 6HD
        country: UK
        street: Balcombe Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: mli.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (044) 074-968-49107 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School MFA2022 CA09 AUT21 Porfolio Website
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.linkedin.com/in/angelo-maoze-l-164192177/
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/profile.php?id=100074191681300
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/ange.m.li/
      - icon: fa-github
        label: GitHub
        url: https://github.com/angelomaozeli
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/angelo-maoze-l-164192177/
  image: ''
  name: Maoze Li
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: accounting.PNG
        subtitle: ACCA affiliate member, ICAS TC member
        title: Accounting Professional
        url:  blogs/aliquam
      - image: finance.jpg
        subtitle: Financial Modelling, Asset Management, Corporate Finance
        title: Finance Enthusiastic
        url: blogs/tempus
      - image: LBS.jpg
        subtitle: Postgraduate Studies in Financial Analysis
        title: London Business School
        url: blogs/magna
      - image: EY.jpg
        subtitle: Pre Full-time Assurance Experience at EY
        title: Pre-EY
        url: blogs/ipsum
      - image: international.jpg
        subtitle: Gained internship experiences in multiple countries across the world
        title: International Business Experiences
        url: blogs/ipsum
      - image: volunteer.jpg
        subtitle: Passionate about giving back to the community
        title: Volunteer
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
